### PR TITLE
Use sensor data QoS

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by mitsudome-r** [comment]
Could anyone review this with a rosbag? 
Maybe @tkimura4?

**Comment by tkimura4** [comment]
@mitsudome-r @wep21 
Where can I get rosbag including VelodyneScan packets?

**Comment by tkimura4** [comment]
$ros2 topic hz /sensing/lidar/top/pointcloud_raw
image

$ros2 topic hz /sensing/lidar/left/pointcloud_raw
image

$ros2 topic hz /sensing/lidar/right/pointcloud_raw
image

$ros2 topic hz /sensing/lidar/rear/pointcloud_raw
image

**Comment by tkimura4** [comment]
top, left... 6Hz
right, rear...10Hz

**Comment by tkimura4** [comment]
$ros2 topic hz /sensing/lidar/left/pointcloud_raw
10Hz(stable)
image

**Comment by tkimura4** [comment]
the topic hz of velodyne left, right, rear(VLP-16) is 10Hz stably.
However, the topic hz of velodyne top(VLP-128) is 7 stably. （I think it's no problem because this may be a CPU performance issue）
image

**Comment by tkimura4** [comment]
Use following rosbag2 https://github.com/ros2/rosbag2/tree/emersonknapp/backport-latest-to-foxy
&
Use following QoS profile
```
File Edit Options Buffers Tools Help                             
/sensing/lidar/top/velodyne_packets:
  reliability: best_effort
  history: keep_last
  depth: 5


```

The topic rate of  /sensing/lidar/top/pointcloud_raw became 10 Hz!
image

**Review by k0suke-murakami — APPROVED** [review]
LGTM

**Pull request merged**
